import type { NewGlossaryTerm } from "@/lib/tauri";

// Curated starter glossary for Russian-language product / user-research interviews.
//
// Why this exists: Russian tech speech is full of anglicisms, transliterations, and brand names
// that whisper.cpp mis-hears (and spells inconsistently). `canonical` is the spelling we want in
// the transcript; `aliases` are the garbled / variant / Latin forms the ASR tends to produce.
// These feed BOTH whisper's initial_prompt (biasing recognition — so ORDER matters, the prompt
// buffer is small and only the lead survives the cap) AND the cleanup post-correction pass.
//
// Convention:
//   - Russian-ized common anglicisms → canonical is the accepted Cyrillic spelling (фича, дедлайн).
//   - Acronyms → canonical is the uppercase Latin form (API, MVP, NPS), aliases the spoken Cyrillic
//     letter-by-letter forms («эй-пи-ай», «эн-пи-эс»).
//   - Brand / tool names → canonical is the original Latin name (Figma, Jira), aliases the Cyrillic
//     transliterations and colloquial forms (телега, джира).
//   - Aliases are REALISTIC: forms whisper actually produces in RU speech (phonetic Cyrillic,
//     common misspellings like «промт», hyphenation variants), lowercase where natural. No
//     near-duplicate spam, no plain-Russian words that would corrupt normal speech when mapped.
//   - notes = a short Russian gloss (shown in UI; only short notes reach the prompts).
//
// Ordered by PRIORITY (most frequent & most-confused first): the whisper initial_prompt cap is
// ~480 chars, so only roughly the first 40–50 canonical terms bias the ASR. Section order below
// reflects how often the vocabulary shows up in real RU product/research interviews. The full
// list still helps via cleanup even past the prompt cap.
export const GLOSSARY_SEED: NewGlossaryTerm[] = [
  // --- ядро: продукт и повседневная рабочая речь (lead the ASR prompt) ---
  { canonical: "фича", aliases: ["feature", "фитча", "фиче", "фичи"], notes: "функция продукта" },
  { canonical: "таска", aliases: ["task", "таск", "таски"], notes: "задача" },
  { canonical: "дедлайн", aliases: ["deadline", "дэдлайн", "дедлайны"], notes: "срок" },
  { canonical: "релиз", aliases: ["release", "релис", "релизы"], notes: "выпуск версии" },
  { canonical: "созвон", aliases: ["колл", "call", "созвониться"], notes: "рабочий звонок" },
  { canonical: "фидбэк", aliases: ["feedback", "фидбек", "обратная связь"], notes: "обратная связь" },
  { canonical: "апрув", aliases: ["approve", "апрувить", "заапрувить"], notes: "согласование" },
  { canonical: "бэклог", aliases: ["backlog", "беклог", "бэк-лог"], notes: "список задач" },
  { canonical: "спринт", aliases: ["sprint", "спринты"], notes: "итерация разработки" },
  { canonical: "юзер", aliases: ["user", "юзеры", "юзера"], notes: "пользователь" },
  { canonical: "продакт", aliases: ["product manager", "продакт-менеджер", "пиэм", "PM", "продакт-овнер"], notes: "менеджер продукта" },
  { canonical: "тимлид", aliases: ["team lead", "тим-лид", "тимлидер"], notes: "лидер команды" },
  { canonical: "саппорт", aliases: ["support", "сапорт", "суппорт"], notes: "служба поддержки" },
  { canonical: "тикет", aliases: ["ticket", "тикеты"], notes: "заявка в поддержку/трекер" },
  { canonical: "аккаунт", aliases: ["account", "акаунт", "экаунт"], notes: "учётная запись" },
  { canonical: "подписка", aliases: ["subscription", "сабскрипшн"], notes: "подписная модель" },
  { canonical: "онбординг", aliases: ["onboarding", "онбоардинг", "онбординк"], notes: "адаптация пользователя" },
  { canonical: "баг", aliases: ["bug", "баги"], notes: "ошибка" },
  { canonical: "деплой", aliases: ["deploy", "деплоить", "деплои"], notes: "развёртывание" },
  { canonical: "продакшен", aliases: ["production", "прод", "продакшн"], notes: "боевая среда" },
  { canonical: "API", aliases: ["апи", "апишка", "эй-пи-ай"], notes: "программный интерфейс" },
  { canonical: "дашборд", aliases: ["dashboard", "дэшборд", "дашбоард"], notes: "панель показателей" },
  { canonical: "админка", aliases: ["admin panel", "админ-панель"], notes: "панель администратора" },
  { canonical: "личный кабинет", aliases: ["ЛК", "элка"], notes: "кабинет пользователя" },
  { canonical: "апдейт", aliases: ["update", "абдейт", "апдейты"], notes: "обновление" },
  { canonical: "стартап", aliases: ["startup", "старт-ап", "стартапы"], notes: "молодая компания" },
  { canonical: "кейс", aliases: ["case", "кейсы"], notes: "пример / сценарий" },
  { canonical: "MVP", aliases: ["эм-ви-пи", "мвп", "минимальный продукт"], notes: "минимально жизнеспособный продукт" },
  { canonical: "роадмап", aliases: ["roadmap", "дорожная карта", "роудмап", "роадмэп"], notes: "план развития" },
  { canonical: "скоуп", aliases: ["scope", "скоп"], notes: "объём работ" },
  { canonical: "инсайт", aliases: ["insight", "инсайты", "инсайд"], notes: "вывод из исследования" },
  { canonical: "боль", aliases: ["pain", "пейн", "пэйн"], notes: "боль / проблема пользователя" },
  { canonical: "гипотеза", aliases: ["hypothesis", "гипотезы"], notes: "проверяемое предположение" },
  { canonical: "метрика", aliases: ["metric", "метрики"], notes: "показатель" },
  { canonical: "конверсия", aliases: ["conversion", "конверсии"], notes: "доля целевых действий" },
  { canonical: "воронка", aliases: ["funnel", "воронка продаж"], notes: "последовательность шагов" },
  { canonical: "отток", aliases: ["churn", "чёрн", "чорн", "чурн"], notes: "отток клиентов (churn)" },
  { canonical: "ретеншн", aliases: ["retention", "ретеншен", "ретенш", "удержание"], notes: "удержание (D1/D7/D30)" },
  { canonical: "вовлечённость", aliases: ["engagement", "энгейджмент", "вовлеченность"], notes: "вовлечённость пользователей" },
  { canonical: "стейкхолдер", aliases: ["stakeholder", "стейкхолдеры"], notes: "заинтересованная сторона" },
  { canonical: "пивот", aliases: ["pivot", "пивотнуть"], notes: "смена стратегии" },
  { canonical: "логин", aliases: ["login", "залогиниться", "логиниться"], notes: "вход в систему" },
  { canonical: "синк", aliases: ["sync", "синкап", "синк-ап"], notes: "короткая сверка с командой" },
  { canonical: "дейлик", aliases: ["daily", "дейли", "дэйлик"], notes: "ежедневная встреча" },
  { canonical: "митинг", aliases: ["meeting", "миттинг"], notes: "рабочая встреча" },

  // --- инструменты и бренды, которые называют почти в каждом интервью ---
  { canonical: "Telegram", aliases: ["телеграм", "телега", "тг", "телеграмм"], notes: "мессенджер" },
  { canonical: "Zoom", aliases: ["зум", "зумм"], notes: "видеозвонки" },
  { canonical: "Slack", aliases: ["слак", "слэк"], notes: "корпоративный мессенджер" },
  { canonical: "WhatsApp", aliases: ["вотсап", "ватсап", "вацап", "воцап"], notes: "мессенджер" },
  { canonical: "Excel", aliases: ["эксель", "иксель", "экселька"], notes: "таблицы Microsoft" },
  { canonical: "Google Sheets", aliases: ["гугл-таблицы", "гугл шитс", "гугл щитс", "гугл таблица"], notes: "онлайн-таблицы" },
  { canonical: "Google Docs", aliases: ["гугл-док", "гугл докс", "гугл документы"], notes: "онлайн-документы" },
  { canonical: "Google Meet", aliases: ["гугл-мит", "гугл мит", "гугл миит"], notes: "видеозвонки" },
  { canonical: "Teams", aliases: ["тимс", "тимз", "майкрософт тимс"], notes: "мессенджер Microsoft" },
  { canonical: "Jira", aliases: ["джира", "жира", "джире"], notes: "трекер задач" },
  { canonical: "Confluence", aliases: ["конфлюенс", "конфлюэнс", "конфлюенц"], notes: "база знаний" },
  { canonical: "Figma", aliases: ["фигма", "фигме", "фигму"], notes: "инструмент дизайна" },
  { canonical: "Miro", aliases: ["миро"], notes: "онлайн-доска" },
  { canonical: "Notion", aliases: ["ноушн", "ноушен", "нотион", "ношн"], notes: "база знаний / заметки" },
  { canonical: "Trello", aliases: ["трелло", "трело"], notes: "канбан-доска" },
  { canonical: "Asana", aliases: ["асана", "азана"], notes: "трекер задач" },
  { canonical: "Linear", aliases: ["линеар", "линир"], notes: "трекер задач" },
  { canonical: "GitHub", aliases: ["гитхаб", "гит хаб"], notes: "хостинг кода" },
  { canonical: "GitLab", aliases: ["гитлаб", "гит лаб"], notes: "хостинг кода / CI" },
  { canonical: "ChatGPT", aliases: ["чат-жпт", "чатгпт", "чат джипити", "чат гпт", "джипити"], notes: "ИИ-ассистент OpenAI" },
  { canonical: "Claude", aliases: ["клод"], notes: "ИИ-ассистент Anthropic" },
  { canonical: "1С", aliases: ["1c", "один эс", "одинэс"], notes: "учётная система" },
  { canonical: "Битрикс24", aliases: ["битрикс", "bitrix", "битрикс 24"], notes: "CRM / корпоративный портал" },
  { canonical: "amoCRM", aliases: ["амо", "амосиарэм", "амо-срм"], notes: "CRM для продаж" },
  { canonical: "CRM", aliases: ["си-ар-эм", "црм", "црмка", "сиарэм"], notes: "система работы с клиентами" },
  { canonical: "ERP", aliases: ["и-ар-пи", "ерп", "е-эр-пэ"], notes: "система управления ресурсами" },
  { canonical: "iOS", aliases: ["айос", "иос", "и-ос"], notes: "ОС Apple" },
  { canonical: "Android", aliases: ["андроид", "андройд"], notes: "ОС Google" },
  { canonical: "iPhone", aliases: ["айфон"], notes: "смартфон Apple" },

  // --- исследования: методы и роли ---
  { canonical: "ресёрч", aliases: ["research", "ресерч", "рисёрч"], notes: "исследование" },
  { canonical: "ресёрчер", aliases: ["researcher", "ресечер", "рисёчер"], notes: "исследователь" },
  { canonical: "кастдев", aliases: ["customer development", "кастомер девелопмент", "кастдэв", "custdev"], notes: "глубинные интервью" },
  { canonical: "глубинное интервью", aliases: ["глубинка", "in-depth interview"], notes: "качественное интервью 1:1" },
  { canonical: "интервью", aliases: ["interview"], notes: "исследовательское интервью" },
  { canonical: "респондент", aliases: ["respondent", "респонденты"], notes: "участник интервью" },
  { canonical: "гайд", aliases: ["guide", "гайды"], notes: "сценарий интервью" },
  { canonical: "модератор", aliases: ["moderator"], notes: "ведущий интервью/теста" },
  { canonical: "скрининг", aliases: ["screening"], notes: "отбор респондентов" },
  { canonical: "скринер", aliases: ["screener", "скринер-анкета"], notes: "анкета отбора" },
  { canonical: "рекрутинг", aliases: ["recruiting", "рекрут", "рекрутмент"], notes: "подбор участников" },
  { canonical: "инсентив", aliases: ["incentive", "инцентив"], notes: "вознаграждение респондента" },
  { canonical: "NDA", aliases: ["эн-ди-эй", "нда"], notes: "соглашение о неразглашении" },
  { canonical: "транскрипт", aliases: ["transcript", "транскрипция"], notes: "расшифровка записи" },
  { canonical: "вербатим", aliases: ["verbatim"], notes: "дословная цитата" },
  { canonical: "кодирование", aliases: ["coding", "кодировка"], notes: "разметка данных исследования" },
  { canonical: "аффинити-карта", aliases: ["affinity map", "аффинити", "аффинити мэп"], notes: "группировка наблюдений" },
  { canonical: "персона", aliases: ["persona", "персоны"], notes: "обобщённый портрет пользователя" },
  { canonical: "сегмент", aliases: ["segment", "сегменты"], notes: "группа пользователей" },
  { canonical: "выборка", aliases: ["sample", "сэмпл", "семпл"], notes: "состав участников" },
  { canonical: "квота", aliases: ["quota", "квоты"], notes: "квота набора респондентов" },
  { canonical: "JTBD", aliases: ["jobs to be done", "джоба", "джобстубидан", "job to be done"], notes: "«работа», ради которой берут продукт" },
  { canonical: "CJM", aliases: ["customer journey", "кастомер джорни", "си-джей-эм", "путь пользователя"], notes: "карта пути пользователя" },
  { canonical: "тачпоинт", aliases: ["touchpoint", "тачпоинты"], notes: "точка контакта" },
  { canonical: "юзкейс", aliases: ["use case", "юз-кейс", "юзкейсы"], notes: "сценарий использования" },
  { canonical: "юзертест", aliases: ["юзабилити-тест", "usability test", "юзер-тест"], notes: "тест интерфейса на пользователях" },
  { canonical: "юзабилити", aliases: ["usability", "юзабельность"], notes: "удобство использования" },
  { canonical: "A/B-тест", aliases: ["аб-тест", "эй-би тест", "ab test", "a/b тест"], notes: "сплит-тест" },
  { canonical: "прототип", aliases: ["prototype", "прото", "прототипы"], notes: "макет" },
  { canonical: "вайрфрейм", aliases: ["wireframe", "варфрейм", "вайрфреймы"], notes: "каркас интерфейса" },
  { canonical: "мокап", aliases: ["mockup", "мокапы", "мок-ап"], notes: "статичный макет" },
  { canonical: "фокус-группа", aliases: ["focus group", "фокусгруппа"], notes: "групповое обсуждение" },
  { canonical: "опрос", aliases: ["survey", "сюрвей", "сервей"], notes: "количественный опрос" },
  { canonical: "опросник", aliases: ["questionnaire", "опросники"], notes: "анкета опроса" },
  { canonical: "полевое исследование", aliases: ["field research", "филд-ресёрч"], notes: "наблюдение «в полях»" },
  { canonical: "дневниковое исследование", aliases: ["diary study", "дайари-стади"], notes: "дневник пользователя" },
  { canonical: "дискавери", aliases: ["discovery", "дискавери-фаза"], notes: "фаза исследования задачи" },
  { canonical: "деливери", aliases: ["delivery", "диливери"], notes: "фаза реализации" },
  { canonical: "блюпринт", aliases: ["blueprint", "сервис-блюпринт", "блю принт"], notes: "карта сервиса" },
  { canonical: "бриф", aliases: ["brief", "брифы"], notes: "постановка задачи" },
  { canonical: "дебриф", aliases: ["debrief", "дебрифинг"], notes: "разбор после сессии" },

  // --- метрики и аналитика (+ инструменты аналитики) ---
  { canonical: "NPS", aliases: ["эн-пи-эс", "нпс"], notes: "индекс лояльности" },
  { canonical: "CSAT", aliases: ["си-сат", "цсат"], notes: "удовлетворённость" },
  { canonical: "CES", aliases: ["си-и-эс", "цес"], notes: "оценка усилий клиента" },
  { canonical: "DAU", aliases: ["дау"], notes: "активные пользователи за день" },
  { canonical: "WAU", aliases: ["дабл-ю-эй-ю"], notes: "активные пользователи за неделю" },
  { canonical: "MAU", aliases: ["мау"], notes: "активные пользователи за месяц" },
  { canonical: "ARPU", aliases: ["арпу"], notes: "средний доход на пользователя" },
  { canonical: "ARPPU", aliases: ["арппу", "арп-пу"], notes: "средний доход на платящего" },
  { canonical: "LTV", aliases: ["эл-ти-ви", "лтв"], notes: "пожизненная ценность клиента" },
  { canonical: "CAC", aliases: ["цак", "си-эй-си", "как-метрика"], notes: "стоимость привлечения" },
  { canonical: "MRR", aliases: ["эм-эр-эр", "мрр"], notes: "месячная регулярная выручка" },
  { canonical: "ARR", aliases: ["а-эр-эр", "эй-ар-ар"], notes: "годовая регулярная выручка" },
  { canonical: "ROI", aliases: ["ар-оу-ай", "рои"], notes: "окупаемость вложений" },
  { canonical: "ROAS", aliases: ["роас"], notes: "окупаемость рекламы" },
  { canonical: "юнит-экономика", aliases: ["unit economics", "юнит экономика", "юнитка"], notes: "экономика на одного клиента" },
  { canonical: "когорта", aliases: ["cohort", "когорты"], notes: "группа по времени прихода" },
  { canonical: "сессия", aliases: ["session", "сессии"], notes: "визит пользователя" },
  { canonical: "трекинг", aliases: ["tracking", "трэкинг", "трекать"], notes: "сбор событий" },
  { canonical: "ивент", aliases: ["event", "эвент", "евент", "ивенты"], notes: "событие в аналитике" },
  { canonical: "атрибуция", aliases: ["attribution", "атрибьюция"], notes: "привязка результата к каналу" },
  { canonical: "North Star", aliases: ["норт стар", "норс стар", "NSM"], notes: "главная метрика продукта" },
  { canonical: "Amplitude", aliases: ["амплитьюд", "амплитуда"], notes: "продуктовая аналитика" },
  { canonical: "Mixpanel", aliases: ["микспанель", "микспанел"], notes: "продуктовая аналитика" },
  { canonical: "Google Analytics", aliases: ["гугл аналитикс", "GA", "джи-эй"], notes: "веб-аналитика" },
  { canonical: "Яндекс.Метрика", aliases: ["яндекс метрика", "яндекс-метрика", "Yandex Metrica"], notes: "веб-аналитика" },
  { canonical: "Power BI", aliases: ["пауэр би-ай", "повер би", "пауэр би"], notes: "BI-отчёты Microsoft" },
  { canonical: "Tableau", aliases: ["табло", "таблоу"], notes: "BI-визуализация" },
  { canonical: "Grafana", aliases: ["графана"], notes: "дашборды мониторинга" },

  // --- рост и бизнес ---
  { canonical: "эквизишн", aliases: ["acquisition", "аквизишн", "акквизишн"], notes: "привлечение пользователей" },
  { canonical: "активация", aliases: ["activation", "активейшн"], notes: "первый успешный опыт" },
  { canonical: "монетизация", aliases: ["monetization", "монетизэйшн"], notes: "модель заработка" },
  { canonical: "триал", aliases: ["trial", "трайал", "триалка"], notes: "пробный период" },
  { canonical: "фримиум", aliases: ["freemium", "фремиум"], notes: "бесплатно + платные функции" },
  { canonical: "пейвол", aliases: ["paywall", "пэйвол", "пейволл"], notes: "платный барьер" },
  { canonical: "апсейл", aliases: ["upsell", "апселл", "ап-сейл"], notes: "продажа более дорогого тарифа" },
  { canonical: "кросс-сейл", aliases: ["cross-sell", "кросс-селл", "кросссейл"], notes: "продажа сопутствующего" },
  { canonical: "средний чек", aliases: ["average check"], notes: "средняя сумма покупки" },
  { canonical: "пайплайн", aliases: ["pipeline", "пайп", "пайплайн продаж"], notes: "поток сделок / этапы" },
  { canonical: "лид", aliases: ["lead", "лиды"], notes: "потенциальный клиент" },
  { canonical: "лидогенерация", aliases: ["лидген", "lead generation"], notes: "привлечение лидов" },
  { canonical: "квалификация", aliases: ["qualification", "квал"], notes: "квалификация лида" },
  { canonical: "демо", aliases: ["demo", "демка", "дэмо"], notes: "демонстрация продукта" },
  { canonical: "питч", aliases: ["pitch", "питчить", "запитчить"], notes: "короткая презентация" },
  { canonical: "оффер", aliases: ["offer", "офер"], notes: "предложение (сделки или работы)" },
  { canonical: "энтерпрайз", aliases: ["enterprise", "интерпрайз", "энтерпрайс"], notes: "крупный корпоративный клиент" },
  { canonical: "SMB", aliases: ["эс-эм-би", "смб"], notes: "малый и средний бизнес" },
  { canonical: "B2B", aliases: ["би-ту-би", "битуби", "б2б", "бэ-два-бэ"], notes: "бизнес для бизнеса" },
  { canonical: "B2C", aliases: ["би-ту-си", "битуси", "б2с"], notes: "бизнес для потребителя" },
  { canonical: "GTM", aliases: ["go-to-market", "гоу-ту-маркет", "го-ту-маркет", "джи-ти-эм"], notes: "стратегия выхода на рынок" },
  { canonical: "ЦА", aliases: ["цэ-а", "цэа"], notes: "целевая аудитория" },
  { canonical: "ревенью", aliases: ["revenue", "ревеню"], notes: "выручка" },
  { canonical: "таргетинг", aliases: ["targeting", "таргет"], notes: "нацеливание рекламы" },
  { canonical: "SEO", aliases: ["сео", "эс-и-о", "сеошка"], notes: "поисковая оптимизация" },
  { canonical: "маркетплейс", aliases: ["marketplace", "маркет-плейс", "маркетплэйс"], notes: "торговая площадка" },

  // --- разработка и доставка ---
  { canonical: "бэкенд", aliases: ["backend", "бекенд", "бэк"], notes: "серверная часть" },
  { canonical: "фронтенд", aliases: ["frontend", "фронт", "фронтэнд"], notes: "клиентская часть" },
  { canonical: "хотфикс", aliases: ["hotfix", "хотфиксы"], notes: "срочное исправление" },
  { canonical: "багфикс", aliases: ["bugfix", "баг-фикс"], notes: "исправление ошибки" },
  { canonical: "фиксить", aliases: ["fix", "пофиксить", "зафиксить"], notes: "исправлять" },
  { canonical: "регресс", aliases: ["regression", "регрессия"], notes: "поломка после изменений" },
  { canonical: "код-ревью", aliases: ["code review", "кодревью", "ревью кода"], notes: "проверка кода" },
  { canonical: "пул-реквест", aliases: ["pull request", "PR", "пиар", "пулреквест"], notes: "запрос на слияние" },
  { canonical: "мёрдж", aliases: ["merge", "мёрж", "мердж", "мерж"], notes: "слияние веток" },
  { canonical: "коммит", aliases: ["commit", "коммитить", "коммиты"], notes: "фиксация изменений" },
  { canonical: "репозиторий", aliases: ["repository", "репа", "репо"], notes: "хранилище кода" },
  { canonical: "легаси", aliases: ["legacy", "легэси"], notes: "устаревший код" },
  { canonical: "техдолг", aliases: ["tech debt", "технический долг", "техдебт"], notes: "накопленные упрощения" },
  { canonical: "рефакторинг", aliases: ["refactoring", "рефактор"], notes: "переработка кода" },
  { canonical: "эндпоинт", aliases: ["endpoint", "эндпоинты"], notes: "точка API" },
  { canonical: "интеграция", aliases: ["integration", "интеграции"], notes: "связка систем" },
  { canonical: "вебхук", aliases: ["webhook", "вебхуки"], notes: "обратный вызов по событию" },
  { canonical: "микросервис", aliases: ["microservice", "микросервисы"], notes: "архитектурный стиль" },
  { canonical: "монолит", aliases: ["monolith", "монолитный"], notes: "единое приложение" },
  { canonical: "инфраструктура", aliases: ["инфра", "infrastructure"], notes: "серверы и окружение" },
  { canonical: "DevOps", aliases: ["девопс", "дев-опс", "девопсы"], notes: "практика эксплуатации" },
  { canonical: "CI/CD", aliases: ["си-ай-си-ди", "сиайсиди"], notes: "непрерывная интеграция/доставка" },
  { canonical: "Docker", aliases: ["докер"], notes: "контейнеризация" },
  { canonical: "Kubernetes", aliases: ["кубернетес", "кубер", "k8s", "кубернетис"], notes: "оркестрация контейнеров" },
  { canonical: "стейджинг", aliases: ["staging", "стейдж"], notes: "тестовая среда" },
  { canonical: "QA", aliases: ["кью-эй", "кьюэй", "куа"], notes: "тестирование / тестировщик" },
  { canonical: "автотесты", aliases: ["autotests", "автотест"], notes: "автоматические тесты" },
  { canonical: "юнит-тест", aliases: ["unit test", "юниттест", "юнит-тесты"], notes: "модульный тест" },
  { canonical: "фича-флаг", aliases: ["feature flag", "фичефлаг", "фиче-флаг"], notes: "флаг включения функции" },
  { canonical: "SDK", aliases: ["эс-ди-кей"], notes: "набор разработчика" },
  { canonical: "SaaS", aliases: ["сас", "эс-эй-эс", "саас"], notes: "ПО как сервис" },
  { canonical: "SQL", aliases: ["эс-ку-эль", "сиквел", "эскюэль"], notes: "язык запросов к БД" },
  { canonical: "скрипт", aliases: ["script", "скрипты"], notes: "небольшая программа" },
  { canonical: "фреймворк", aliases: ["framework", "фрэймворк", "фреймворки"], notes: "программный каркас" },
  { canonical: "опенсорс", aliases: ["open source", "опен-сорс", "оупенсорс"], notes: "открытый код" },
  { canonical: "логи", aliases: ["logs", "лог"], notes: "журнал событий" },
  { canonical: "алерт", aliases: ["alert", "алёрт", "алерты"], notes: "оповещение мониторинга" },
  { canonical: "аптайм", aliases: ["uptime", "ап-тайм"], notes: "время доступности" },
  { canonical: "даунтайм", aliases: ["downtime", "даун-тайм"], notes: "простой сервиса" },
  { canonical: "латенси", aliases: ["latency", "лэтенси", "задержка"], notes: "задержка отклика" },
  { canonical: "кэш", aliases: ["cache", "кеш", "кэширование"], notes: "промежуточное хранилище" },
  { canonical: "токен", aliases: ["token", "токены"], notes: "ключ доступа; единица текста LLM" },
  { canonical: "краш", aliases: ["crash", "крэш", "крашится"], notes: "падение приложения" },
  { canonical: "лаг", aliases: ["lag", "лаги", "лагает"], notes: "подтормаживание" },
  { canonical: "фриз", aliases: ["freeze", "фризит", "фризы"], notes: "зависание" },
  { canonical: "раскатка", aliases: ["rollout", "роллаут", "выкатка", "раскатить", "выкатить"], notes: "постепенный выпуск" },
  { canonical: "спека", aliases: ["spec", "спек"], notes: "спецификация" },
  { canonical: "он-колл", aliases: ["on-call", "онколл"], notes: "дежурство" },
  { canonical: "он-прем", aliases: ["on-premise", "он-премис", "онпрем"], notes: "развёртывание у клиента" },
  { canonical: "стори", aliases: ["story", "юзерстори", "user story", "сторя"], notes: "пользовательская история" },
  { canonical: "эпик", aliases: ["epic", "эпики"], notes: "крупная задача" },
  { canonical: "эстимейт", aliases: ["estimate", "эстимейты", "оценка"], notes: "оценка трудоёмкости" },
  { canonical: "велосити", aliases: ["velocity"], notes: "скорость команды" },
  { canonical: "Postman", aliases: ["постман", "постмен"], notes: "инструмент для API" },
  { canonical: "VS Code", aliases: ["вс-код", "вэ-эс код", "вижуал студио код"], notes: "редактор кода" },

  // --- дизайн и UX ---
  { canonical: "UX", aliases: ["ю-икс", "юикс", "юэкс"], notes: "пользовательский опыт" },
  { canonical: "UI", aliases: ["ю-ай", "юай"], notes: "интерфейс" },
  { canonical: "юзер-флоу", aliases: ["user flow", "юзерфлоу"], notes: "пользовательский поток" },
  { canonical: "дизайн-система", aliases: ["design system", "дизайн система"], notes: "библиотека компонентов" },
  { canonical: "дизайн-токены", aliases: ["design tokens", "токены дизайна"], notes: "переменные стилей" },
  { canonical: "лендинг", aliases: ["landing", "лэндинг", "лендос"], notes: "посадочная страница" },
  { canonical: "попап", aliases: ["popup", "поп-ап", "попапы"], notes: "всплывающее окно" },
  { canonical: "модалка", aliases: ["modal", "модал"], notes: "модальное окно" },
  { canonical: "дропдаун", aliases: ["dropdown", "дроп-даун"], notes: "выпадающий список" },
  { canonical: "чекбокс", aliases: ["checkbox", "чек-бокс", "чекбоксы"], notes: "флажок" },
  { canonical: "тоггл", aliases: ["toggle", "тогл"], notes: "переключатель" },
  { canonical: "тултип", aliases: ["tooltip", "тултипы", "тул-тип"], notes: "всплывающая подсказка" },
  { canonical: "плейсхолдер", aliases: ["placeholder", "плэйсхолдер"], notes: "текст-заглушка в поле" },
  { canonical: "эмпти-стейт", aliases: ["empty state", "эмпти стейт"], notes: "пустое состояние экрана" },
  { canonical: "хедер", aliases: ["header", "хэдер"], notes: "шапка страницы" },
  { canonical: "футер", aliases: ["footer", "футтер"], notes: "подвал страницы" },
  { canonical: "брейкпоинт", aliases: ["breakpoint", "брэйкпоинт"], notes: "точка адаптива" },
  { canonical: "адаптив", aliases: ["responsive", "респонсив"], notes: "адаптивная вёрстка" },
  { canonical: "грид", aliases: ["grid", "гриды"], notes: "сетка макета" },
  { canonical: "скролл", aliases: ["scroll", "скрол", "скроллить"], notes: "прокрутка" },
  { canonical: "свайп", aliases: ["swipe", "свайпнуть"], notes: "жест смахивания" },
  { canonical: "таб", aliases: ["tab", "табы"], notes: "вкладка" },
  { canonical: "скриншот", aliases: ["screenshot", "скрин", "скриншоты"], notes: "снимок экрана" },
  { canonical: "пуш", aliases: ["push", "пуши", "пуш-уведомление"], notes: "push-уведомление" },
  { canonical: "десктоп", aliases: ["desktop", "дэсктоп"], notes: "настольная версия" },

  // --- ИИ и машинное обучение ---
  { canonical: "ИИ", aliases: ["AI", "эй-ай", "эйай", "аи"], notes: "искусственный интеллект" },
  { canonical: "нейросеть", aliases: ["нейронка", "нейросетка", "neural network"], notes: "нейронная сеть" },
  { canonical: "LLM", aliases: ["эл-эл-эм", "ллм"], notes: "большая языковая модель" },
  { canonical: "GPT", aliases: ["джи-пи-ти", "жпт", "гпт"], notes: "семейство моделей OpenAI" },
  { canonical: "промпт", aliases: ["prompt", "промт", "промпты", "промты"], notes: "запрос к модели" },
  { canonical: "промптинг", aliases: ["prompting", "промтинг"], notes: "составление промптов" },
  { canonical: "агент", aliases: ["agent", "агенты"], notes: "автономный ИИ-агент" },
  { canonical: "RAG", aliases: ["рэг", "раг", "ар-эй-джи"], notes: "поиск + генерация" },
  { canonical: "файнтюнинг", aliases: ["fine-tuning", "файнтюн", "файн-тюнинг"], notes: "дообучение модели" },
  { canonical: "эмбеддинг", aliases: ["embedding", "эмбединг", "эмбеддинги"], notes: "векторное представление" },
  { canonical: "галлюцинация", aliases: ["hallucination", "галюцинация"], notes: "выдумка модели" },
  { canonical: "инференс", aliases: ["inference"], notes: "выполнение модели" },
  { canonical: "контекстное окно", aliases: ["context window", "окно контекста"], notes: "объём контекста модели" },
  { canonical: "ML", aliases: ["эм-эль", "машин-лёрнинг", "машинлернинг", "machine learning"], notes: "машинное обучение" },
  { canonical: "Copilot", aliases: ["копайлот", "копилот", "ко-пилот"], notes: "ИИ-ассистент разработчика" },
  { canonical: "Gemini", aliases: ["джемини", "гемини", "джеминай"], notes: "ИИ-модель Google" },
  { canonical: "чат-бот", aliases: ["chatbot", "чатбот"], notes: "диалоговый бот" },
  { canonical: "дата-сайентист", aliases: ["data scientist", "датасаентист", "дата саентист"], notes: "специалист по данным" },

  // --- встречи и оргречь ---
  { canonical: "стендап", aliases: ["standup", "стэндап"], notes: "ежедневная встреча команды" },
  { canonical: "ретро", aliases: ["retrospective", "ретроспектива"], notes: "ретроспектива спринта" },
  { canonical: "планинг", aliases: ["planning", "плэннинг"], notes: "планирование спринта" },
  { canonical: "груминг", aliases: ["grooming", "рефайнмент", "refinement"], notes: "разбор бэклога" },
  { canonical: "ван-он-ван", aliases: ["one-on-one", "уан-он-уан", "ван он ван"], notes: "встреча один на один" },
  { canonical: "каденция", aliases: ["cadence", "каденс"], notes: "ритм встреч/релизов" },
  { canonical: "квартал", aliases: ["quarter"], notes: "отчётный период" },
  { canonical: "OKR", aliases: ["окей-ар", "окр", "оу-кей-ар", "окиары"], notes: "цели и ключевые результаты" },
  { canonical: "KPI", aliases: ["кей-пи-ай", "кипиай"], notes: "ключевой показатель" },
  { canonical: "перформанс-ревью", aliases: ["performance review", "перф-ревью", "перфоманс-ревью"], notes: "оценка сотрудника" },
  { canonical: "HR", aliases: ["эйчар", "эйч-ар", "хэ-эр"], notes: "кадровая служба" },
  { canonical: "си-левел", aliases: ["C-level", "с-левел", "силевел"], notes: "топ-менеджмент" },
  { canonical: "фаундер", aliases: ["founder", "фаундеры"], notes: "основатель" },
  { canonical: "кофаундер", aliases: ["co-founder", "ко-фаундер"], notes: "сооснователь" },
  { canonical: "CEO", aliases: ["си-и-о", "сиэо"], notes: "генеральный директор" },
  { canonical: "CTO", aliases: ["си-ти-о", "сити-о"], notes: "технический директор" },
  { canonical: "CPO", aliases: ["си-пи-о", "сипио"], notes: "директор по продукту" },
  { canonical: "ASAP", aliases: ["асап"], notes: "как можно скорее" },
  { canonical: "фоллоу-ап", aliases: ["follow-up", "фоллоуап", "фолоуап"], notes: "письмо/действия по итогам" },
  { canonical: "брейншторм", aliases: ["brainstorm", "брэйншторм", "брейн-шторм"], notes: "мозговой штурм" },
  { canonical: "воркшоп", aliases: ["workshop", "воркшопы"], notes: "рабочая сессия" },
  { canonical: "таймлайн", aliases: ["timeline", "тайм-лайн"], notes: "план по времени" },
  { canonical: "майлстоун", aliases: ["milestone", "майлстон"], notes: "контрольная точка" },
  { canonical: "блокер", aliases: ["blocker", "блокеры"], notes: "блокирующая проблема" },
  { canonical: "приоритизация", aliases: ["prioritization", "приоритезация"], notes: "расстановка приоритетов" },
  { canonical: "бенчмарк", aliases: ["benchmark", "бенч", "бэнчмарк"], notes: "эталон для сравнения" },
  { canonical: "алайнмент", aliases: ["alignment", "элайнмент", "заалайниться"], notes: "согласованность" },
  { canonical: "эскалация", aliases: ["escalation", "эскалировать"], notes: "подъём проблемы наверх" },
];
