// Standalone HTML report for a cycle ("wave") — the shareable deliverable (v3 F2).
//
// buildCycleReportHtml() assembles a single self-contained HTML string: inline CSS in the
// design-direction spirit but LIGHT theme (print/share-friendly) — Inter/system stack, one
// indigo accent, hairline borders, tabular numerals. No external assets, no scripts, so it
// opens anywhere and prints cleanly. All interpolated text goes through esc() — XSS-safe by
// construction (the synthesis markdown is converted by a tiny converter that escapes first).
//
// downloadHtmlReport() saves it via the same Blob + transient-anchor mechanism the .md
// exports in synthesis-tab/diff-tab already use (works in Tauri's webview and the browser
// preview alike — no fs plugin needed).

import { tr } from "@/lib/i18n";
import type {
  CoverageRow,
  Cycle,
  DiffEntry,
  DiffRow,
  DiffStatus,
  Finding,
  Goal,
  InterviewRow,
  SynthesisRow,
} from "@/lib/tauri";

const STR = {
  ru: {
    researchWave: "Волна исследований",
    interviews: (n: number) =>
      `${n} ${plural(n, "интервью", "интервью", "интервью")}`,
    executiveSummary: "Резюме",
    findingsByGoal: "Выводы по целям",
    noFindingsForGoal: "По этой цели выводов не найдено.",
    confidence: "уверенность",
    confHigh: "высокая",
    confMedium: "средняя",
    confLow: "низкая",
    quotes: (n: number) => `${n} ${plural(n, "цитата", "цитаты", "цитат")}`,
    interviewsCount: (n: number) =>
      `${n} ${plural(n, "интервью", "интервью", "интервью")}`,
    recommendation: "Рекомендация",
    diffTitle: "Что изменилось vs предыдущей волны",
    statusNew: "Новое",
    statusChanged: "Изменено",
    statusDropped: "Убрано",
    statusUnchanged: "Без изменений",
    coverageTitle: "Покрытие гайда по интервью",
    coverageScore: "балл покрытия",
    noCoverage: "не проверялось",
    openQuestions: "Открытые вопросы",
    generatedBy: (date: string) => `Сгенерировано InterviewLab · ${date}`,
    unknownInterview: (id: string) => `Интервью ${id}`,
  },
  en: {
    researchWave: "Research wave",
    interviews: (n: number) => `${n} interview${n === 1 ? "" : "s"}`,
    executiveSummary: "Executive summary",
    findingsByGoal: "Findings by goal",
    noFindingsForGoal: "No findings surfaced for this goal.",
    confidence: "confidence",
    confHigh: "high",
    confMedium: "medium",
    confLow: "low",
    quotes: (n: number) => `${n} quote${n === 1 ? "" : "s"}`,
    interviewsCount: (n: number) => `${n} interview${n === 1 ? "" : "s"}`,
    recommendation: "Recommendation",
    diffTitle: "What changed vs the previous wave",
    statusNew: "New",
    statusChanged: "Changed",
    statusDropped: "Dropped",
    statusUnchanged: "Unchanged",
    coverageTitle: "Guide coverage per interview",
    coverageScore: "coverage score",
    noCoverage: "not checked",
    openQuestions: "Open questions",
    generatedBy: (date: string) => `Generated by InterviewLab · ${date}`,
    unknownInterview: (id: string) => `Interview ${id}`,
  },
};

// Russian plural helper (1 / 2-4 / 5+).
function plural(n: number, one: string, few: string, many: string): string {
  const m10 = n % 10;
  const m100 = n % 100;
  if (m10 === 1 && m100 !== 11) return one;
  if (m10 >= 2 && m10 <= 4 && (m100 < 12 || m100 > 14)) return few;
  return many;
}

// HTML-escape every interpolated string. The single choke point that keeps the report
// XSS-safe by construction.
function esc(s: string): string {
  return s.replace(
    /[&<>"']/g,
    (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        c
      ]!,
  );
}

// --- Tiny markdown → HTML converter ---------------------------------------------
// `marked` isn't a dependency and the React renderers (streamdown/remark) don't emit
// strings, so this is a deliberately small hand converter covering what the synthesis
// artifact actually uses: headings, unordered/ordered lists, bold/italic/inline code,
// paragraphs. Everything is escaped BEFORE inline markup is applied.

function inlineMd(s: string): string {
  let x = esc(s);
  x = x.replace(/`([^`]+)`/g, "<code>$1</code>");
  x = x.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
  x = x.replace(/(^|[^*])\*([^*\s][^*]*)\*/g, "$1<em>$2</em>");
  x = x.replace(/(^|[^_])_([^_\s][^_]*)_/g, "$1<em>$2</em>");
  return x;
}

export function miniMarkdownToHtml(md: string): string {
  const lines = md.replace(/\r\n/g, "\n").split("\n");
  const out: string[] = [];
  let para: string[] = [];
  let list: "ul" | "ol" | null = null;

  const flushPara = () => {
    if (para.length > 0) {
      out.push(`<p>${inlineMd(para.join(" "))}</p>`);
      para = [];
    }
  };
  const closeList = () => {
    if (list) {
      out.push(`</${list}>`);
      list = null;
    }
  };

  for (const raw of lines) {
    const line = raw.trimEnd();
    if (!line.trim()) {
      flushPara();
      closeList();
      continue;
    }
    const h = /^(#{1,6})\s+(.*)$/.exec(line);
    if (h) {
      flushPara();
      closeList();
      const lvl = h[1].length;
      out.push(`<h${lvl}>${inlineMd(h[2])}</h${lvl}>`);
      continue;
    }
    const ul = /^\s*[-*+]\s+(.*)$/.exec(line);
    if (ul) {
      flushPara();
      if (list !== "ul") {
        closeList();
        out.push("<ul>");
        list = "ul";
      }
      out.push(`<li>${inlineMd(ul[1])}</li>`);
      continue;
    }
    const ol = /^\s*\d+[.)]\s+(.*)$/.exec(line);
    if (ol) {
      flushPara();
      if (list !== "ol") {
        closeList();
        out.push("<ol>");
        list = "ol";
      }
      out.push(`<li>${inlineMd(ol[1])}</li>`);
      continue;
    }
    closeList();
    para.push(line.trim());
  }
  flushPara();
  closeList();
  return out.join("\n");
}

// --- Report assembly --------------------------------------------------------------

export type CycleReportInput = {
  cycle: Cycle;
  synthesis: SynthesisRow;
  goals: Goal[];
  diff?: DiffRow | null;
  // interview_id → its coverage row (null = never checked). Optional section.
  coverageByInterview?: Record<string, CoverageRow | null>;
  interviews: InterviewRow[];
};

// Confidence value → localized label (falls back to the raw value).
function confLabel(c: string | null | undefined): string {
  const t = tr(STR);
  const map: Record<string, string> = {
    high: t.confHigh,
    medium: t.confMedium,
    low: t.confLow,
  };
  if (!c) return "—";
  return map[c.toLowerCase()] ?? c;
}

function confidenceBadge(confidence: string): string {
  const t = tr(STR);
  const c = confidence.toLowerCase();
  return `<span class="badge conf-${esc(c)}"><span class="dot"></span>${esc(
    t.confidence,
  )}: ${esc(confLabel(c))}</span>`;
}

function statusBadge(status: DiffStatus): string {
  const t = tr(STR);
  const label: Record<DiffStatus, string> = {
    new: t.statusNew,
    changed: t.statusChanged,
    dropped: t.statusDropped,
    unchanged: t.statusUnchanged,
  };
  return `<span class="badge st-${esc(status)}"><span class="dot"></span>${esc(
    label[status],
  )}</span>`;
}

function findingHtml(f: Finding, titleFor: (id: string) => string): string {
  const t = tr(STR);
  const evidence = f.evidence
    .map(
      (e) =>
        `<li class="quote">“${esc(e.quote)}”<span class="src">${esc(
          titleFor(e.interview_id),
        )}</span></li>`,
    )
    .join("");
  const rec = f.recommendation
    ? `<p class="rec"><strong>${esc(t.recommendation)}:</strong> ${esc(
        f.recommendation,
      )}</p>`
    : "";
  return `<div class="finding">
  <p class="statement"><span class="fid">${esc(f.id)}</span>${esc(f.statement)}</p>
  <p class="meta-row">${confidenceBadge(f.confidence)}<span class="count">${esc(
    t.interviewsCount(f.support_count),
  )}</span><span class="count">${esc(t.quotes(f.evidence.length))}</span></p>
  ${evidence ? `<ul class="quotes">${evidence}</ul>` : ""}
  ${rec}
</div>`;
}

function diffEntryHtml(e: DiffEntry): string {
  const t = tr(STR);
  const conf =
    e.confidence || e.prev_confidence
      ? `<span class="count">${esc(t.confidence)}: ${esc(
          confLabel(e.prev_confidence),
        )} → ${esc(confLabel(e.confidence))}</span>`
      : "";
  const why = e.why ? `<p class="why">${esc(e.why)}</p>` : "";
  return `<div class="diff-entry">
  <p class="statement">${esc(e.statement)}</p>
  <p class="meta-row">${statusBadge(e.status)}${conf}</p>
  ${why}
</div>`;
}

// The report's inline stylesheet: light theme, Inter/system stack, indigo accent
// (#5e6ad2), hairline borders, tabular numerals. Kept flat and calm — no shadows,
// no gradients — so it reads like the product, translated to paper.
const REPORT_CSS = `
:root {
  --bg: #ffffff; --text: #1a1c22; --text-2: #5c5f6a; --muted: #8b8e98;
  --border: #e6e7eb; --accent: #5e6ad2;
  --green: #1f9d6f; --amber: #b27d20; --red: #ce4b3c;
}
* { box-sizing: border-box; }
body {
  margin: 0; background: var(--bg); color: var(--text);
  font: 14px/1.6 "Inter", -apple-system, "Segoe UI", system-ui, sans-serif;
  -webkit-font-smoothing: antialiased;
}
.page { max-width: 760px; margin: 0 auto; padding: 48px 32px 64px; }
.num { font-variant-numeric: tabular-nums; }
header.report { border-bottom: 1px solid var(--border); padding-bottom: 20px; margin-bottom: 32px; }
.eyebrow { font-size: 11px; letter-spacing: 0.08em; text-transform: uppercase; color: var(--accent); font-weight: 600; }
h1 { font-size: 24px; font-weight: 600; letter-spacing: -0.02em; margin: 6px 0 4px; }
.meta { font-size: 12px; color: var(--muted); font-variant-numeric: tabular-nums; }
section { margin: 0 0 36px; }
h2.section { font-size: 15px; font-weight: 600; letter-spacing: -0.01em; margin: 0 0 4px; }
h2.section::after { content: ""; display: block; width: 32px; height: 2px; background: var(--accent); margin-top: 6px; border-radius: 1px; }
.section-wrap { border-top: 1px solid var(--border); padding-top: 20px; }
.prose h1, .prose h2, .prose h3, .prose h4, .prose h5, .prose h6 { font-weight: 600; letter-spacing: -0.01em; margin: 18px 0 6px; }
.prose h1 { font-size: 17px; } .prose h2 { font-size: 15px; } .prose h3 { font-size: 14px; }
.prose p { margin: 8px 0; } .prose ul, .prose ol { margin: 8px 0; padding-left: 22px; }
.prose li { margin: 3px 0; }
.prose code { font-family: "JetBrains Mono", ui-monospace, monospace; font-size: 12px; background: #f4f4f6; border: 1px solid var(--border); border-radius: 4px; padding: 1px 4px; }
.goal { margin: 20px 0 0; }
.goal-head { display: flex; align-items: baseline; gap: 8px; margin-bottom: 8px; }
.gid, .fid { font-family: ui-monospace, "JetBrains Mono", monospace; font-variant-numeric: tabular-nums; font-size: 11px; color: var(--accent); font-weight: 600; }
.fid { color: var(--muted); font-weight: 500; margin-right: 8px; }
.goal-head h3 { font-size: 14px; font-weight: 600; margin: 0; }
.finding, .diff-entry { border-left: 2px solid var(--border); padding: 2px 0 2px 14px; margin: 12px 0; }
.statement { margin: 0 0 6px; font-size: 14px; }
.meta-row { display: flex; flex-wrap: wrap; gap: 12px; align-items: center; margin: 0 0 6px; }
.badge { display: inline-flex; align-items: center; gap: 6px; font-size: 11px; border: 1px solid var(--border); border-radius: 999px; padding: 1px 9px; color: var(--text-2); }
.badge .dot { width: 6px; height: 6px; border-radius: 999px; background: var(--muted); }
.conf-high .dot, .st-new .dot { background: var(--green); }
.conf-high, .st-new { color: var(--green); border-color: rgba(31,157,111,0.35); }
.conf-medium .dot, .st-changed .dot { background: var(--amber); }
.st-changed { color: var(--amber); border-color: rgba(178,125,32,0.35); }
.st-dropped .dot { background: var(--red); }
.st-dropped { color: var(--red); border-color: rgba(206,75,60,0.35); }
.count { font-size: 11px; color: var(--muted); font-variant-numeric: tabular-nums; }
.quotes { list-style: none; margin: 6px 0; padding: 0; }
.quote { font-size: 12.5px; color: var(--text-2); font-style: italic; margin: 6px 0; padding-left: 12px; border-left: 2px solid var(--border); }
.quote .src { display: block; font-style: normal; font-size: 11px; color: var(--muted); margin-top: 2px; }
.rec { font-size: 12.5px; color: var(--text-2); background: #f7f7f9; border: 1px solid var(--border); border-radius: 6px; padding: 8px 12px; margin: 8px 0 0; }
.why { font-size: 12px; color: var(--muted); margin: 0; }
.summary-line { font-size: 13.5px; color: var(--text-2); border: 1px solid var(--border); border-radius: 8px; padding: 10px 14px; margin: 0 0 8px; }
table.coverage { width: 100%; border-collapse: collapse; margin-top: 12px; }
table.coverage th { text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: var(--muted); font-weight: 500; border-bottom: 1px solid var(--border); padding: 6px 8px; }
table.coverage td { border-bottom: 1px solid var(--border); padding: 8px; font-size: 13px; vertical-align: middle; }
td.score { width: 220px; }
.score-num { font-variant-numeric: tabular-nums; font-weight: 600; margin-right: 10px; }
.bar { display: inline-block; width: 140px; height: 3px; border-radius: 2px; background: #eeeef1; vertical-align: middle; }
.bar i { display: block; height: 100%; border-radius: 2px; background: var(--accent); }
.na { color: var(--muted); font-size: 12px; }
footer.report { border-top: 1px solid var(--border); margin-top: 48px; padding-top: 14px; font-size: 11px; color: var(--muted); }
@media print { .page { padding: 0; } }
`;

// Build the standalone HTML report for a cycle. Sections: title/date/wave meta,
// executive summary (the markdown artifact, converted), findings by goal (confidence
// badges + evidence), the wave-over-wave diff (when present), and per-interview coverage
// scores (when provided). Pure function of its inputs — safe to unit-test.
export function buildCycleReportHtml(input: CycleReportInput): string {
  const t = tr(STR);
  const { cycle, synthesis, goals, diff, coverageByInterview, interviews } =
    input;

  const titleFor = (id: string): string => {
    const found = interviews.find((i) => i.id === id);
    return found?.title ?? t.unknownInterview(id.slice(0, 8));
  };

  const dateStr = new Date(synthesis.created_at).toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // --- Executive summary: the (possibly user-edited) markdown artifact. -----------
  const summaryMd =
    synthesis.content_md.trim() || synthesis.doc.executive_summary || "";
  const summaryHtml = summaryMd
    ? `<section>
  <h2 class="section">${esc(t.executiveSummary)}</h2>
  <div class="prose">${miniMarkdownToHtml(summaryMd)}</div>
</section>`
    : "";

  // --- Findings by goal. -----------------------------------------------------------
  const docGoals = synthesis.doc.goals.length > 0 ? synthesis.doc.goals : goals;
  const byGoal = new Map<string, Finding[]>();
  for (const f of synthesis.doc.findings) {
    const arr = byGoal.get(f.goal_id) ?? [];
    arr.push(f);
    byGoal.set(f.goal_id, arr);
  }
  const goalsHtml = docGoals
    .map((g) => {
      const findings = byGoal.get(g.id) ?? [];
      const body =
        findings.length === 0
          ? `<p class="na">${esc(t.noFindingsForGoal)}</p>`
          : findings.map((f) => findingHtml(f, titleFor)).join("\n");
      return `<div class="goal">
  <div class="goal-head"><span class="gid">${esc(g.id)}</span><h3>${esc(
    g.text,
  )}</h3></div>
  ${body}
</div>`;
    })
    .join("\n");

  // --- Open questions (small, only when present). -----------------------------------
  const openQs = synthesis.doc.open_questions ?? [];
  const openQuestionsHtml =
    openQs.length > 0
      ? `<section>
  <h2 class="section">${esc(t.openQuestions)}</h2>
  <div class="prose"><ul>${openQs.map((q) => `<li>${esc(q)}</li>`).join("")}</ul></div>
</section>`
      : "";

  // --- Diff vs previous wave (optional). --------------------------------------------
  let diffHtml = "";
  if (diff && diff.doc.by_goal.length > 0) {
    const goalBlocks = diff.doc.goals
      .map((g) => {
        const entries =
          diff.doc.by_goal.find((x) => x.goal_id === g.id)?.entries ?? [];
        if (entries.length === 0) return "";
        return `<div class="goal">
  <div class="goal-head"><span class="gid">${esc(g.id)}</span><h3>${esc(
    g.text,
  )}</h3></div>
  ${entries.map(diffEntryHtml).join("\n")}
</div>`;
      })
      .filter(Boolean)
      .join("\n");
    diffHtml = `<section>
  <h2 class="section">${esc(t.diffTitle)}</h2>
  ${diff.doc.summary ? `<p class="summary-line">${esc(diff.doc.summary)}</p>` : ""}
  ${goalBlocks}
</section>`;
  }

  // --- Per-interview coverage scores (optional). --------------------------------------
  let coverageHtml = "";
  if (coverageByInterview && interviews.length > 0) {
    const rows = interviews
      .map((i) => {
        const cov = coverageByInterview[i.id];
        const cell = cov
          ? `<span class="score-num">${Math.round(cov.doc.score)}</span><span class="bar"><i style="width:${Math.max(
              0,
              Math.min(100, Math.round(cov.doc.score)),
            )}%"></i></span>`
          : `<span class="na">${esc(t.noCoverage)}</span>`;
        return `<tr><td>${esc(i.title)}</td><td class="score">${cell}</td></tr>`;
      })
      .join("\n");
    coverageHtml = `<section>
  <h2 class="section">${esc(t.coverageTitle)}</h2>
  <table class="coverage">
    <thead><tr><th></th><th>${esc(t.coverageScore)}</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
</section>`;
  }

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(cycle.name)}</title>
<style>${REPORT_CSS}</style>
</head>
<body>
<div class="page">
<header class="report">
  <div class="eyebrow">${esc(t.researchWave)}</div>
  <h1>${esc(cycle.name)}</h1>
  <div class="meta">${esc(dateStr)} · ${esc(t.interviews(interviews.length))}</div>
</header>
${summaryHtml}
<section>
  <h2 class="section">${esc(t.findingsByGoal)}</h2>
  ${goalsHtml}
</section>
${diffHtml}
${coverageHtml}
${openQuestionsHtml}
<footer class="report">${esc(t.generatedBy(new Date().toLocaleDateString()))}</footer>
</div>
</body>
</html>`;
}

// Save an HTML string as a file via a Blob + transient anchor — the same mechanism the
// existing .md exports use (works in the Tauri webview and the browser preview alike).
export function downloadHtmlReport(html: string, filename: string): void {
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// A filesystem-safe report filename derived from the cycle name.
export function reportFileName(cycleName: string): string {
  const slug = cycleName
    .trim()
    .replace(/[\\/:*?"<>|]+/g, "")
    .replace(/\s+/g, "-")
    .slice(0, 60);
  return `${slug || "cycle"}-report.html`;
}
